Repository prgrms-be-devcourse/BE-03-InterMark, pull requests merged in 2023-01, with the labels that each got.

#4 [FEAT] : 엔티티 설계
  build.gradle
  src/main/java/com/prgrms/be/intermark/domain/actor/Actor.java
  src/main/java/com/prgrms/be/intermark/domain/actor/Gender.java
  src/main/java/com/prgrms/be/intermark/domain/casting/Casting.java
  src/main/java/com/prgrms/be/intermark/domain/performance/Genre.java
  src/main/java/com/prgrms/be/intermark/domain/performance/Performance.java
  src/main/java/com/prgrms/be/intermark/domain/performance/PerformanceDetailImage.java
  src/main/java/com/prgrms/be/intermark/domain/performance/PerformanceRating.java
  src/main/java/com/prgrms/be/intermark/domain/performance_stadium/PerformanceStadium.java
  src/main/java/com/prgrms/be/intermark/domain/schedule/Schedule.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/ScheduleSeat.java
  src/main/java/com/prgrms/be/intermark/domain/seat/Seat.java
  src/main/java/com/prgrms/be/intermark/domain/seat/SeatGrade.java
  src/main/java/com/prgrms/be/intermark/domain/stadium/Stadium.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/Ticket.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/TicketStatus.java
  src/main/java/com/prgrms/be/intermark/domain/user/Social.java
  src/main/java/com/prgrms/be/intermark/domain/user/User.java
  src/main/java/com/prgrms/be/intermark/domain/user/UserRole.java
Labels: Team-Marco

#44 [HOTFIX] : ScheduleSeat 테이블 명 변경
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/ScheduleSeat.java
Labels: FIX

#46 [FIX] : Seat 엔티티 필드 명, 컬럼 명 변경
  src/main/java/com/prgrms/be/intermark/domain/seat/Seat.java
Labels: FIX

#53 [FEAT] : 공연 리스트 조회 기능 구현.
  src/main/java/com/prgrms/be/intermark/domain/performance/controller/PerformanceAdminController.java
  src/main/java/com/prgrms/be/intermark/domain/performance/dto/PerformanceInfoResponseDTO.java
  src/main/java/com/prgrms/be/intermark/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/prgrms/be/intermark/domain/performance/service/PerformanceAdminService.java
Labels: FEAT

#60 [FIX] : 깃헙 액션이 동작하지 않는 것 수정
  .github/workflows/ci.yml
Labels: FIX

#52 [FEAT] : 예매 관련 API 페어 프로그래밍
  src/main/java/com/prgrms/be/intermark/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/ScheduleSeat.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/controller/ScheduleSeatApiController.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/dto/ScheduleSeatFindRequestDTO.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/dto/ScheduleSeatResponseDTO.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/dto/ScheduleSeatResponseDTOs.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/repository/ScheduleSeatRepository.java
  src/main/java/com/prgrms/be/intermark/domain/schedule_seat/service/ScheduleSeatService.java
  src/main/java/com/prgrms/be/intermark/domain/seat/repository/SeatRepository.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/Ticket.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/controller/TicketController.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/dto/TicketCreateRequestDTO.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/dto/TicketDeleteResponseDto.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/dto/TicketFindResponseDTO.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/dto/TicketFindResponseDTOs.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/repository/TicketRepository.java
  src/main/java/com/prgrms/be/intermark/domain/ticket/service/TicketService.java
  src/main/java/com/prgrms/be/intermark/domain/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: FEAT

#54 [FEAT] : 스케줄 등록 및 수정 API 구현
  src/main/java/com/prgrms/be/intermark/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/prgrms/be/intermark/domain/performance_stadium/repository/PerformanceStadiumRepository.java
  src/main/java/com/prgrms/be/intermark/domain/schedule/Schedule.java
  src/main/java/com/prgrms/be/intermark/domain/schedule/controller/ScheduleController.java
  src/main/java/com/prgrms/be/intermark/domain/schedule/dto/ScheduleRequestDTO.java
  src/main/java/com/prgrms/be/intermark/domain/schedule/service/ScheduleService.java
  src/main/java/com/prgrms/be/intermark/domain/stadium/repository/StadiumRepository.java
Labels: FEAT
